name: Build

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: My Parameter
  push:
    branches: [ "vsphere-2023" ]
    
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set Up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Go Mod
      run: go mod tidy        
    - name: Go Mod
      run: go mod vendor
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2.12
      with:
        image: hypershift-vsphere
        tags: may2023 ${{ github.sha }}
        dockerfiles: ./Dockerfile
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/ocp-splat
        username: ocp-splat+splat_team_push
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
